<a href="https://colab.research.google.com/github/cardavid11/tensorflow_certification/blob/main/100%20problems/Problem_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Great! Starting with Problem 1, we'll focus on basic TensorFlow operations. Here's your first challenge:

### Problem 1: Basic TensorFlow Operations

#### Task Description:
Write a Python program using TensorFlow to perform the following tensor operations:

1. **Tensor Creation**: Create two tensors `A` and `B` of shape (3,3) with random values.
2. **Addition**: Add tensors `A` and `B`.
3. **Multiplication**: Multiply tensors `A` and `B`.
4. **Matrix Multiplication**: Perform matrix multiplication between `A` and `B`.
5. **Reshaping**: Reshape tensor `A` to shape (9,1).
6. **Reduce Mean**: Compute the mean of tensor `B`.
7. **Gradient Tape**: Use TensorFlow's GradientTape to compute the derivative of the sum of elements in `A` with respect to each element in `A`.

#### Skills Tested:
- Understanding of TensorFlow APIs for tensor creation and manipulation.
- Familiarity with basic mathematical operations in TensorFlow.
- Comprehension of automatic differentiation using GradientTape.

Once you have completed the task, you can share your code here for review or ask for hints if you encounter difficulties. Let's get started!

In [2]:
import tensorflow as tf

In [3]:
# 1. Tensor Creation: Create two tensors A and B of shape (3,3) with random values.
A = tf.constant(tf.random.normal(shape=(3,3)))
B = tf.constant(tf.random.normal(shape=(3,3)))

In [5]:
# 2. Addition: Add tensors A and B.
tf.add(A,B)

# It is possible to also implement
# A + B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.3466971 , -0.52222455,  1.9870858 ],
       [ 0.32553068,  0.48125368, -1.5262746 ],
       [ 0.61124194, -0.27508557,  0.1826456 ]], dtype=float32)>

In [6]:
# 3. Multiplication: Multiply tensors A and B.
tf.multiply(A,B)

# It is possible to also implement
# A * B

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.40711665, -0.8789911 ,  0.97234285],
       [-0.01430334,  0.01875202,  0.4311034 ],
       [ 0.08576703, -0.02959998, -0.00272162]], dtype=float32)>

In [ ]:
# 4. Matrix Multiplication: Perform matrix multiplication between A and B.
tf.matmul(A,B)

# It is possible to also implement
# A @ B

In [8]:
#5 Reshaping: Reshape tensor A to shape (9,1).
tf.reshape(A, (9,1))

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.45821702,  0.7121147 ,  1.1151354 ],
        [-0.0392146 ,  0.43848854, -1.1520783 ],
        [ 0.39301172,  0.08272523, -0.01385075]], dtype=float32)>,
 <tf.Tensor: shape=(9, 1), dtype=float32, numpy=
 array([[ 0.45821702],
        [ 0.7121147 ],
        [ 1.1151354 ],
        [-0.0392146 ],
        [ 0.43848854],
        [-1.1520783 ],
        [ 0.39301172],
        [ 0.08272523],
        [-0.01385075]], dtype=float32)>)

In [9]:
# 6 Reduce Mean: Compute the mean of tensor B.
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=float32, numpy=0.06848012>

In [10]:
# 7 Gradient Tape: Use TensorFlow's GradientTape to compute the derivative of the sum of elements in A with respect to each element in A.

### Understanding the Task: Gradient Tape

#### Task Breakdown
# - **What is Gradient Tape?**: TensorFlow's `GradientTape` is a tool for automatic differentiation. It records operations performed in forward pass and then uses that record to compute gradients in the backward pass.
# - **Your Task**: Use `GradientTape` to compute the derivative of the sum of elements in tensor `A` with respect to each element in `A`.

#### Detailed Explanation
# 1. **Record Operations**:
#    - First, you need to create a context using `tf.GradientTape()`. Inside this context, you will define the operation for which you want to compute the derivative.
#    - In this case, the operation is the sum of all elements in tensor `A`.

# 2. **Compute the Derivative**:
#    - The derivative you need to compute is how much the sum of all elements in `A` changes when you change each individual element in `A`.
#    - In mathematical terms, if `S` is the sum of all elements in `A`, you are computing ∂S/∂A[i][j] for each element A[i][j].

# 3. **Why Is This Useful?**:
#    - Understanding how to compute such derivatives is crucial for gradient-based optimization algorithms, which are the backbone of training neural networks.

#### Code

with tf.GradientTape() as tape:
    # Ensure that A is being watched by the tape
    tape.watch(A)

    # Define the operation: Sum of elements in A
    S = tf.reduce_sum(A)

# Compute the gradient (derivative) of S with respect to A
gradients = tape.gradient(S, A)

# gradients now contains the derivative of the sum S with respect to each element in A

# This code will give you the gradient of the sum of all elements in tensor `A` with respect to each element in `A`. Each element in the `gradients` tensor corresponds to the partial derivative of the sum with respect to the corresponding element in `A`.